replicaCount: 1
image:
  repository: containers.pkg.github.com/slipperypenguin/release-notifier/release-notifier
  digest: sha256:1234
  tag: v0.1.3
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi
revisionHistoryLimit: 20
namespace: igloo
slack: xxxx
github: xxxx
