apiVersion: v1
kind: Secret
metadata:
  app: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  slack: {{ .Values.slack | b64enc | quote }}
  github: {{ .Values.github | b64enc | quote }}
